### ISSUE TITLE
Bugs with needinfo showing up in query

### ISSUE THREAD

**Issue by agrover** [mozilla-necko/necko-triage#3]
Bugs with needinfo are showing up in [bug list](https://mozilla-necko.github.io/necko-triage/) "Untriaged bugs (from May 4 '20 and on)".

For example, https://bugzilla.mozilla.org/show_bug.cgi?id=1576602 is needinfo and so shouldn't show up.

This leads to a huge number of bugs in the list, and the triager having to look at and then ignore ones with needinfo. 

It would be good if either 1) query didn't return bugs with needinfo or 2) needinfo status was displayed on the web page.

**Comment by mayhemer** [comment]
When I use the provided [query link](https://bugzilla.mozilla.org/rest/bug?include_fields=id,summary,status&chfield=%5BBug%20creation%5D&chfieldfrom=2016-06-01&component=DOM%3A%20Networking&component=Networking&component=Networking%3A%20Cache&component=Networking%3A%20Cookies&component=Networking%3A%20DNS&component=Networking%3A%20Domain%20Lists&component=Networking%3A%20File&component=Networking%3A%20FTP&component=Networking%3A%20HTTP&component=Networking%3A%20JAR&component=Networking%3A%20WebSockets&email1=intermittent-bug-filer%40mozilla.bugs&email2=wptsync%40mozilla.bugs&emailreporter1=1&emailreporter2=1&emailtype1=notequals&emailtype2=notequals&f1=OP&f10=CP&f11=flagtypes.name&f2=OP&f3=cf_status_firefox_nightly&f4=cf_status_firefox_beta&f5=cf_status_firefox_release&f6=cf_status_firefox_esr&f7=bug_type&f8=CP&f9=bug_severity&j1=OR&n11=1&o11=substring&o3=equals&o4=equals&o5=equals&o6=equals&o7=equals&o9=equals&product=Core&resolution=---&status_whiteboard=%5C%5Bnecko%5C-.%2A%5C%5D&status_whiteboard_type=notregexp&v11=needinfo&v3=---&v4=---&v5=---&v6=---&v7=defect&v9=--) it shows only 7 bugs.

It's really painful to convert the query to a JSON w/o making a mistake.  I'll try to do it once again.

**Comment by agrover** [comment]
Seems fixed! Closing. Thanks.
